import random
#
# ps9pr4.py - Problem Set 9, Problem 4
#
# Name: Sarah Larbi
# Email: slarbi@bu.edu
#
# Partner's name: Sheryn Chung
# Partner's email: sherync@bu.edu

#1.

def create_dictionary(filename):
    """ that takes a string representing the name of a text file, and that returns a dictionary of key-value pairs in which:
    each key is a word encountered in the text file
    the corresponding value is a list of words that follow the key word in the text file."""
    file = open(filename, 'r')
    text = file.read() 
    file.close()

    words = text.split()
    d = {}
    current_word = '$'

    for next_word in words:
        if current_word not in d:
            d[current_word] = [next_word]

        else:
            d[current_word] += [next_word]

        if '.' in next_word or '!' in next_word or '?' in next_word:
            current_word = '$'

        else:
            current_word = next_word
    return d



#2.

def generate_text(word_dict, num_words):
    """takes as parameters a dictionary of word transitions (generated by the create_dictionary function) named word_dict and a positive integer named num_words. The function should use word_dict to generate and print a string of num_words words."""

    wordcount = num_words
    current_word = random.choice(word_dict['$'])
    print(current_word, end=' ')
 #   print(current_word)
 #   next_word = random.choice(wordlist)
 #   print(next_word)


    while wordcount > 0:
        if '!' in current_word or '?' in current_word or '.' in current_word:
            current_word = random.choice(word_dict['$'])
            wordcount -= 1
            print(current_word, end= ' ')

        else:
            wordlist = word_dict[current_word]
            current_word = random.choice(wordlist)
            wordcount -= 1
            print(current_word, end= ' ')
